{"version":3,"sources":["ErrorWithCause.js"],"names":["hasProperty","require","ErrorWithCause","Error","constructor","message","options","cause","isNetworkError","module","exports"],"mappings":"AAAA,MAAMA,WAAW,GAAGC,OAAO,CAAC,eAAD,CAA3B;;AAEA,MAAMC,cAAN,SAA6BC,KAA7B,CAAmC;AACjCC,EAAAA,WAAW,CAAEC,OAAF,EAAWC,OAAX,EAAyB;AAAA,QAAdA,OAAc;AAAdA,MAAAA,OAAc,GAAJ,EAAI;AAAA;;AAClC,UAAMD,OAAN;AACA,SAAKE,KAAL,GAAaD,OAAO,CAACC,KAArB;;AACA,QAAI,KAAKA,KAAL,IAAcP,WAAW,CAAC,KAAKO,KAAN,EAAa,gBAAb,CAA7B,EAA6D;AAC3D,WAAKC,cAAL,GAAsB,KAAKD,KAAL,CAAWC,cAAjC;AACD;AACF;;AAPgC;;AAUnCC,MAAM,CAACC,OAAP,GAAiBR,cAAjB","sourcesContent":["const hasProperty = require('./hasProperty')\n\nclass ErrorWithCause extends Error {\n  constructor (message, options = {}) {\n    super(message)\n    this.cause = options.cause\n    if (this.cause && hasProperty(this.cause, 'isNetworkError')) {\n      this.isNetworkError = this.cause.isNetworkError\n    }\n  }\n}\n\nmodule.exports = ErrorWithCause\n"]}